language: java
jdk:
- oraclejdk8
install: mvn install

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  branches:
  only: 
    - master
  on:  
    tags: true
