language: java
jdk:
- oraclejdk8
install: mvn install
api_key:
    secure: 16bf43783ec91e042b37918d8654c6f6d23d25b0
branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

before_deploy:
  - export RELEASE_JAR_FILE=$(build/libs/*.jar)
  - echo "Deploying $RELEASE_JAR_FILE to GitHub"

deploy:
  provider: releases
  file_glob: true
  file: "Plik wykonywalny"
  skip_cleanup: true
  on:  
    all_branches: true
