language: java
jdk:
- oraclejdk8
install: mvn install

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

before_deploy:
  - export RELEASE_JAR_FILE=$(build/libs/*.jar)
  - echo "Deploying $RELEASE_JAR_FILE to GitHub"

deploy:
  provider: releases
  api_key :
    secure: ${GH_Token}
  file_glob: true
  file: "Plik wykonywalny"
  skip_cleanup: true
  on:  
    all_branches: true
